name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install black
        run: |
          python -m pip install black
      - name: Check code formatting with black
        run: |
          black --check --diff .

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pylint
        run: |
          python -m pip install pylint
      - name: Run Pylint
        run: |
          pylint .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    needs: lint  # Ensure linting happens before tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage pytest-cov # Ensure pytest-cov is installed
      - name: Set PYTHONPATH for robot module
        run: |
          export PYTHONPATH=$(pwd)  # Set PYTHONPATH to the current directory (root where robot.py is)
      - name: Run Tests with Coverage
        run: |
          coverage run test_login.py
          coverage report
      - name: Upload Coverage to Codecov (Optional, if you use Codecov)
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Use a secret for security
